#!/bin/sh
# Demonstrated for fun by guys at ihaveapc.com
# Ping a standard website with output suppressed, if ping completes then display success else failure

# Which Interface do you want to check/fix
wlan='wlan0'

echo "Checking internet connectivity..."
ping -c 5 192.168.1.87>>/dev/null

if [ $? -eq  0 ]
then
	echo "Able to reach internet, yay!"
else
	echo " Not able to check internet connectivity!"
	#/usr/bin/php /var/www/heating/control2drayton.php
    ifdown $wlan
    sleep 5
    ifup --force $wlan
    ifconfig $wlan | grep "inet addr"
fi
