#!/bin/sh
# root@raspberrypi:/home/pi# /opt/vc/bin/vcgencmd measure_temp
# temp=44.4'C
# wiki.stocksy.co.uk/wiki/Raspberry_Pi_onboard_temperature_sensors

echo "** .70 System Temp"
echo "Updated $(date)"
/opt/vc/bin/vcgencmd measure_temp

